puppetlabs/puppet-resource_api

lib/puppet/resource_api/base_context.rb
Remove repeated ': ' in each log entry
=> Fix resource_api logging format

lib/puppet/resource_api/base_context.rb, spec/puppet/resource_api/base_context_spec.rb
Adds processed()
Updates processing() to only accept a single resource title, and to raise if multiple are passed.
=> base_context processing and processed logging methods

lib/puppet/resource_api/simple_provider.rb
Previously when no `is` value was passed to set, the lookup for the
cached values would have gone wrong. This commit now properly checks
for `name`, and calls this out in the docs, too.
=> SimpleProvider: fix `is`-lookup and docs

lib/puppet/resource_api.rb, spec/acceptance/device_spec.rb, spec/puppet/resource_api_spec.rb
This uses Puppet4+ pops to parse and check datatypes. This allows types
to use the full range of expressibility when declaring attributes.
=> (PDK-536) Proper datatype parsing and checking

lib/puppet/resource_api/glue.rb, spec/puppet/resource_api/glue_spec.rb
Prior to this commit resource output was improperly formatted
```
ntp_server { "1.2.3.4":
ensure => ':present',
key => '"94"',
minpoll => '"4"',
maxpoll => '"14"',
prefer => 'true',
source_interface => '"Vlan1"',
}
```
vs
```
ntp_server { "1.2.3.4":
ensure => 'present',
key => '94',
minpoll => '4',
maxpoll => '14',
prefer => true,
source_interface => 'Vlan1',
}
```
=> (main) Fixup to_manifest output

README.md, lib/puppet/resource_api.rb, spec/acceptance/noop_spec.rb, spec/fixtures/test_module/lib/puppet/provider/test_noop_support/test_noop_support.rb, spec/fixtures/test_module/lib/puppet/type/test_noop_support.rb, spec/fixtures/test_module/spec/unit/puppet/provider/test_noop_support/test_noop_support_spec.rb, spec/puppet/resource_api_spec.rb
See https://github.com/DavidS/puppet-specifications/blob/resourceapi/language/resource-api/README.md#provider-feature-supports_noop for a definition of the feature.
This commit only contains the expected outline of the tests, to structure
what needs to be done.
=> (PDK-513) implement `supports_noop`

lib/puppet/resource_api/puppet_context.rb, spec/puppet/resource_api/puppet_context_spec.rb
Before: Notice: Puppet::ResourceApi::PuppetContext::PuppetLogger: title_provider[foo]: Creating: Creating 'foo' with {:namevar=>"foo", :ensure=>:present, :ip=>"127.0.1.1"}
After: Notice: title_provider[foo]: Creating: Creating 'foo' with {:namevar=>"foo", :ensure=>:present, :ip=>"127.0.1.1"}
=> Improve logging output

README.md
The `rake release[]` task pushes to the specified remote. The changes
here make sure that this actually works.
As a side-effect this also allows two people doing a release at the same
time to notice that earlier.
=> Update release prep notes

README.md, lib/puppet/resource_api.rb, spec/acceptance/device_spec.rb, spec/acceptance/validation_spec.rb, spec/fixtures/test_module/lib/puppet/provider/device_provider/device_provider.rb, spec/fixtures/test_module/lib/puppet/provider/test_autorequire/test_autorequire.rb, spec/fixtures/test_module/lib/puppet/provider/test_noop_support/test_noop_support.rb, spec/fixtures/test_module/lib/puppet/provider/test_simple_get_filter/test_simple_get_filter.rb, spec/fixtures/test_module/lib/puppet/provider/test_validation/test_validation.rb, spec/fixtures/test_module/lib/puppet/provider/title_provider/title_provider.rb, spec/fixtures/test_module/spec/unit/puppet/provider/test_autorequire/test_autorequire_spec.rb, spec/fixtures/test_module/spec/unit/puppet/provider/test_noop_support/test_noop_support_spec.rb, spec/fixtures/test_module/spec/unit/puppet/provider/test_validation/test_validation_spec.rb, spec/fixtures/test_module/spec/unit/puppet/provider/title_provider/title_provider_spec.rb, spec/puppet/resource_api/base_context_spec.rb, spec/puppet/resource_api_spec.rb
Tripping over puppet's behaviour for handling newvalue values, rsapi
would accidentally pass symbols for `Enum[absent, present]` ensures.
The unit and integration tests did not agree on whether `absent` and
`present` should be strings or symbols. Puppet itself is calling for
a string as a value for `Enum`s, and in the implementation those two
were only symbols because of a special case in the setup of the two.
This commit fixes this behaviour to always use string. This makes it
consistent with the rest of the API, and reduces the amount of noise
developers have to remember when working with values passed from us.
=> (PDK-911) Fix handling of `ensure` values from symbols to strings

lib/puppet/resource_api/base_context.rb, lib/puppet/resource_api/glue.rb, lib/puppet/resource_api/simple_provider.rb
In some cases when puppet is not yet loaded, those files would
throw unnecessary errors. This fixes that.
=> Make ruby files individually loadable without puppet

.travis.yml
Hey there,
I'm a Customer Support Engineer @ Travis CI and @DavidS wrote asking if it was possible to speed up the jruby jobs.
It's not great but here's my attempt. The idea is to cache the ~/.rvm directory and install jruby manually instead of using the `rvm:` key in the .travis.yml file.
Let's follow up in the e-mail you sent.
=> Cache ~/.rvm for jruby jobs

contrib/pre-commit, lib/puppet/resource_api/simple_provider.rb, spec/puppet/resource_api/simple_provider_spec.rb
Also patches pre-commit hook script, so that it doesn't commit unstaged files
=>  (PDK-924) Throw when SimpleProvider is used with unensurable type

contrib/pre-commit, lib/puppet/resource_api.rb, spec/puppet/resource_api_spec.rb
Also contains:
Better messaging when provider.get does not return correctly
(maint) Pre-commit hook should now properly deal with stages changes
=> (PDK-996) Provide better messaging when type cannot be resolved

lib/puppet/util/network_device/simple/device.rb, spec/puppet/util/network_device/simple/device_spec.rb
Previously `SimpleDevice` was only looking for a credentials file to load.
This allows for tasks to re-use the same code as providers to connect to
devices.
=> Allow `SimpleDevice` to be initialized with a config hash

Gemfile, README.md
Based on our meeting last week, this commit reorganized the first section to make the steps clearer.
=> (puppet-resource_api) Minor changes to README

lib/puppet/resource_api.rb, spec/acceptance/simple_get_filter_spec.rb, spec/fixtures/test_module/lib/puppet/provider/test_simple_get_filter/test_simple_get_filter.rb, spec/puppet/resource_api_spec.rb
Corrected to allow the provider to decide on the subset to return when no specific resource is provided.
Will now correctly fetch the required resource from the cache or make a new call via the provider if it is not found in the cache.
=> (MODULES-7679) Fix up simple_get_filter feature

README.md, lib/puppet/resource_api.rb, lib/puppet/resource_api/type_definition.rb, spec/acceptance/composite_namevar_spec.rb, spec/fixtures/test_module/lib/puppet/provider/composite_namevar/composite_namevar.rb, spec/fixtures/test_module/lib/puppet/type/composite_namevar.rb, spec/puppet/resource_api_spec.rb
This change facilitates composite namevar functionality.
=> (PDK-1150) Allow providers to override :title when retrieving resources

lib/puppet/resource_api.rb
Using the value straight from the type definition leads to aliasing
problems, where anyone accessing this value and mutating it (e.g.
adding an element to an array), would modify the actual default value.
Using Marshal dump/load in a block creates a new instance everytime
the default value is evaluated, and will address this issue completely.
=> (maint) create a new default value instance on every access

README.md
* Rename `sync.yml` to `.sync.yml` in the walkthrough...It was a bit misleading.
* Add missing log line following the `pdk new provider foo` command
=> Update README walkthrough

Gemfile, lib/puppet/resource_api/simple_provider.rb, spec/fixtures/test_module/lib/puppet/provider/composite_namevar/composite_namevar.rb, spec/puppet/resource_api/simple_provider_spec.rb
Create, Update and Delete now receive a hash containing all the namevar values and the composite title if the type has multiple namevars
=> (PDK-1143) Allow SimpleProvider to handle multiple namevars

spec/fixtures/test_module/lib/puppet/type/composite_namevar.rb, spec/puppet/resource_api_spec.rb
seperator changed to separator
It should be also changed in other places such in here here https://github.com/puppetlabs/puppet-specifications/blob/master/language/resource-api/README.md
=> Minor spelling fix

lib/puppet/resource_api.rb
If there is a top level module with same name as a type which gets loaded before the type gets defined then this will trigger a false positive on the `last_module.const_defined?` check causing an `uninitialized constant` error.
This change will no longer do a recursive check and only care about the local namespace this way avoiding the false positive.
=> (PDK-1209) setting inherited const_defined lookup to false

lib/puppet/resource_api.rb, spec/puppet/resource_api_spec.rb
Same as #132, there are more const_get and const_defined? calls that
need to ignore inherited names.
=> (PDK-1209) Fix the other call-sites of const_defined? and const_get

lib/puppet/resource_api/data_type_handling.rb
Fixes failures to load the resource API in puppet-agent before the
puppet module has been declared.
https://github.com/puppetlabs/puppet-resource_api/pull/138 broke ruby smoke tests in puppet-agent acceptance last night; This change seems to fix the problem (but I'll close this if you'd rather address it some other way)
=> (maint) Predeclare Puppet module before ResourceApi

lib/puppet/resource_api.rb, lib/puppet/resource_api/parameter.rb, lib/puppet/resource_api/property.rb, lib/puppet/resource_api/read_only_parameter.rb, lib/puppet/resource_api/value_creator.rb, spec/puppet/resource_api/parameter_spec.rb, spec/puppet/resource_api/property_spec.rb, spec/puppet/resource_api/read_only_parameter_spec.rb, spec/puppet/resource_api/value_creator_spec.rb
In this proposal the PR the changes were extraction of parameter logic to:
- `Puppet::ResourceApi::Property`
- `Puppet::ResourceApi::ReadOnlyParameter`
- `Puppet::ResourceApi::Parameter`
and movement of value defaults and aliases logic to
- `Puppet::ResourceApi::ValueCreator`
Commits are in smaller chunks and can be changed / squashed.
@DavidS if you have any changes, suggestions please let me know. I can adjust the code.
=> Move parameter and property logic to separate classes

lib/puppet/resource_api/version.rb
The puppet-agent release automation assumes repositories know what the
NEXT version of the project will be. This will be maintained
automatically by our automation going forward, but needs to be
manually fixed up this time.
=> (packaging) Update version to 1.6.3

lib/puppet/resource_api/version.rb
The puppet-agent release automation assumes repositories know what the
NEXT version of the project will be. This will be maintained
automatically by our automation going forward, but needs to be
manually fixed up this time.
=> (packaging) Update version to 1.7.0

.rspec, lib/puppet/resource_api.rb, lib/puppet/resource_api/type_definition.rb, spec/puppet/resource_api/base_context_spec.rb, spec/puppet/resource_api/io_context_spec.rb, spec/puppet/resource_api/puppet_context_spec.rb, spec/puppet/resource_api/type_definition_spec.rb, spec/puppet/resource_api_spec.rb, spec/spec_helper.rb
This has been split out and updated from pr #141
=> (maint) Validate Type Schema

lib/puppet/resource_api.rb, lib/puppet/resource_api/transport.rb, lib/puppet/resource_api/type_definition.rb, spec/puppet/resource_api/base_type_definition_spec.rb, spec/puppet/resource_api/transport_schema_def_spec.rb, spec/puppet/resource_api/transport_spec.rb, spec/puppet/resource_api/type_definition_spec.rb, spec/puppet/resource_api_spec.rb
Follows on from #142 which will need to be merged first.
=>  (FM-7597) RSAPI Transport register function

lib/puppet/resource_api/transport.rb, lib/puppet/resource_api/transport/wrapper.rb, spec/acceptance/device_spec.rb, spec/fixtures/test_module/lib/puppet/transport/schema/test_device.rb, spec/fixtures/test_module/lib/puppet/transport/test_device.rb, spec/puppet/resource_api/transport/wrapper_spec.rb, spec/puppet/resource_api/transport_spec.rb
Will take a call for a Device and if available call a suitable Transport instead
=> (FM-7674) Add a Transport wrapper class

lib/puppet/resource_api/base_context.rb, lib/puppet/resource_api/io_context.rb, lib/puppet/resource_api/puppet_context.rb, lib/puppet/resource_api/transport/wrapper.rb, spec/fixtures/test_module/lib/puppet/util/network_device/test_device/device.rb, spec/puppet/resource_api/base_context_spec.rb, spec/puppet/resource_api/io_context_spec.rb, spec/puppet/resource_api/puppet_context_spec.rb
Using this accessor providers can talk directly to the transport
without having to go through the `Device` at all.
=> (FM-7726) implement `context.transport` to provide access

lib/puppet/resource_api.rb, lib/puppet/resource_api/transport.rb, lib/puppet/resource_api/transport/wrapper.rb, spec/puppet/resource_api/transport_spec.rb, spec/puppet/resource_api_spec.rb
=> Transport support for device specific providers

README.md, lib/puppet/resource_api/version.rb, misc/ANNOUNCEMENT_TEMPLATE.md
Hopefully this is the last manual bump to the Resource API version.
This PR bumps to the next version and also removes the "v" from version number
=> (PA-2496) Bump version and remove v from version number

lib/puppet/resource_api/glue.rb, spec/integration/resource_api_spec.rb, spec/puppet/resource_api/glue_spec.rb
bolt's `get_resources` uses the `libexec/query_resources.rb` to retrieve
resources as json from the target nodes. Especially https://github.com/puppetlabs/bolt/blob/7dec6e49d66c7f9ae06088d46ee3330de0ed2fed/libexec/query_resources.rb#L71
causes `ResourceShims` to fail as they did not implement `to_json`.
This integration test models what `libexec/query_resources.rb` is doing.
The added `to_json(*)` method now passes this test, and - shown in manual
testing - works for bolt.
=> (FM-7839) Implement `to_json` method for ResourceShim

.travis.yml, Gemfile
These changes enable the current JRuby 1.7 build to complete. It appears that the current `master` branch is using a cache which has hidden the failures, which are evident when building against a new fork.
=> (maint) Fixup Gemfile for JRuby 1.7 installs

lib/puppet/resource_api/glue.rb, spec/puppet/resource_api/glue_spec.rb
The only conflict was related to these two commits:
https://github.com/puppetlabs/puppet-resource_api/commit/83323bff2ee52d3d51730b5b3c3e846027299398
https://github.com/puppetlabs/puppet-resource_api/commit/be6d8dd56266e3a0236a216c6ee80a728fcc0214
First one implements "to_json" the second one implements "to_hash".
Based on the commit messages, I've made the assumption that both methods need to get into master.
=> (maint) Merge 1.6.x to master 

.travis.yml, Gemfile, lib/puppet/resource_api/glue.rb, spec/integration/resource_api_spec.rb, spec/puppet/resource_api/glue_spec.rb
* (maint) Fixup Gemfile for JRuby 1.7 installs
needed for running travis on 1.6.x changes
* (FM-7839) Implement 'to_json' method for ResourceShim for bolt
required to support bolt
Both changes are cherry-picks from the master branch and both should have originally been applied to 1.6.x and merged up instead.
=> (maint) backport minor fixes from master to 1.6.x

lib/puppet/resource_api.rb, spec/puppet/resource_api/base_context_spec.rb, spec/puppet/resource_api/puppet_context_spec.rb, spec/puppet/resource_api_spec.rb
This implements the changes specified in https://github.com/puppetlabs/puppet-specifications/pull/141
> The text and examples have been inconsistent with how `desc` vs `docs`
> has been handled. This change fixes the text and examples to all show
> and require `desc`, but accept `docs` in places where we showed it
> previously.
=> (maint) implement `desc`/`docs` fallback

README.md, lib/puppet/resource_api/transport.rb, spec/puppet/resource_api/transport_spec.rb
This is an initial draft of the solution. Still needs tests and validation.
=> (PUP-9747) Relax validation for bolt

spec/puppet/resource_api/transport_spec.rb, spec/puppet/resource_api_spec.rb
These test fixes are fixes for unclean tests uncovered by `--rand` test ordering.
=> (maint) test fixes

.rspec, spec/puppet/resource_api/type_definition_spec.rb, spec/puppet/resource_api_spec.rb
The test leakage fixed in #174 was only detected by
changing the test order. Removing the seed will ensure that different
test orderings are tested, leading to a more robust test suite as new
issues are discovered and fixed.
This already has found another issue fixed here too.
=> (maint) make test order really random

Rakefile, lib/puppet/resource_api.rb, lib/puppet/resource_api/glue.rb, lib/puppet/resource_api/simple_provider.rb, spec/acceptance/composite_namevar_spec.rb, spec/acceptance/namevar_spec.rb, spec/fixtures/test_module/lib/puppet/provider/composite_namevar/composite_namevar.rb, spec/fixtures/test_module/lib/puppet/provider/multiple_namevar/multiple_namevar.rb, spec/fixtures/test_module/lib/puppet/type/composite_namevar.rb, spec/integration/resource_api_spec.rb, spec/puppet/resource_api/glue_spec.rb, spec/puppet/resource_api/simple_provider_spec.rb, spec/puppet/resource_api_spec.rb
This is a series of changes to make the composite namevar behaviour work. See the individual commits for details and https://github.com/puppetlabs/puppet-specifications/pull/140 for the specification changes/clarifications.
=> (MODULES-9428) make the composite namevar implementation usable

lib/puppet/resource_api/transport.rb, spec/integration/resource_api/transport_spec.rb, spec/puppet/resource_api/transport_spec.rb, spec/puppet/resource_api_spec.rb, spec/spec_helper.rb
To test out, run `rake spec_prep` and use the following setup in pry:
```
require 'puppet'
require 'puppet/resource_api/transport'
require 'puppet/settings'
Puppet.initialize_settings
Puppet[:modulepath] = 'spec/fixtures/modules'
Puppet::ResourceApi::Transport.list_all_transports('production')
```
=> (SERVER-2470) list_all_transports implementation for puppetserver

.travis.yml
It appears that Travis have updated their default distro from `trusty` to `xenial`. This brought with it updates to the ruby and bundler versions used. Pinning back to `trusty` in the short term with a long term fix to investigate the compatibility between Jruby and the new `xenial` build environment.
=> (maint) Pin both Jruby cells to use `dist: trusty`

lib/puppet/resource_api/transport.rb, spec/puppet/resource_api/transport_spec.rb
When running in puppetserver for the [environment_transports](https://github.com/puppetlabs/puppetserver/blob/master/documentation/puppet-api/v3/environment_transports.markdown)
API, the Resource API would cache registered transport schemas forever.
This meant that deploying a new module version and running the usual
environment cache cleaning scripts would not update the transport schema.
With this change, we push the transport cache into an ObjectIdCacheAdapter
around the environment, which will be cleaned up by the internal utilities.
=> (FM-8092) Fix caching scope of transport schemas

lib/puppet/resource_api/transport.rb, spec/integration/resource_api/transport_spec.rb
It turned out that the environment object in the puppetserver does not survive for longer than a request, making the ObjectIdCacheAdapter creating a new cache everytime. Since the autoloader was using `require` to load schemas, this lead to the cache not being refresehd, and the API would return wrong (empty) results.
This change fixes this by not caching at all and using `load` instead of `require`, so that the schemas are always freshly loaded.
=> (FM-8553) Remove all caching from list_all_transports

lib/puppet/resource_api/transport.rb, spec/integration/resource_api/transport_spec.rb, spec/puppet/resource_api/transport_spec.rb
When exposing attributes in the UI, they currently need to be alphabetised by their name, since the transmission through APIs does not preserve key order of the connection_info hash.
To facilitate showing attributes in the order defined by the module author, this change embeds the key-insertion order from the TypeDefinition into the API response.
=> (FM-8336) Capture and expose attribute ordering from transport schema

lib/puppet/resource_api.rb, lib/puppet/resource_api/base_context.rb, spec/acceptance/failure_spec.rb, spec/fixtures/test_module/lib/puppet/provider/test_failure/test_failure.rb, spec/fixtures/test_module/lib/puppet/type/test_failure.rb, spec/puppet/resource_api/base_context_spec.rb, spec/spec_helper.rb
Ensure that context.failed? is reset after a failure encountered
during a flush so following resources do not falsely indicate
they encountered an error.
=> Reset context.failed? between resources

lib/puppet/resource_api.rb, spec/puppet/resource_api_spec.rb
=> (PUP-10025) fix top-level docs output from `puppet describe`

lib/puppet/resource_api.rb, lib/puppet/resource_api/type_definition.rb, spec/fixtures/test_module/lib/puppet/type/multiple_namevar.rb, spec/puppet/resource_api_spec.rb
This ensures that title values, if returned from a multi-namevar
provider, meet the following consistency checks:
* The title value must match one of the title patterns
* The values parsed from the title pattern match must match the
values returned from the provider for the respective namevars.
=> Add title consistency checks for multi-namevar providers

.dependency_decisions.yml, .travis.yml, spec/acceptance/device_spec.rb
See https://github.com/pivotal/LicenseFinder/issues/665 for reference
=> Update dependency_decisions for LicenseFinder 6.0; Fix deprecation warning with outdated win32-service gem pulled in by puppet

docs/hands-on-lab/01-installing-prereqs.md
This commit updates the configuration file to point to the official Puppet VS Code Extension `puppet.puppet-vscode`
=> (maint) Update Puppet VS Code Extension ID

.travis.yml, appveyor.yml, lib/puppet/resource_api/glue.rb, spec/acceptance/device_spec.rb, spec/puppet/resource_api/glue_spec.rb
- add `to_hiera_hash` method (invoking existing to_hierayaml)
- add acceptance test running `puppet device --resource --to_yaml`
- remove testing on puppet4 and jruby 1.7: those versions have been out of support for a while now and upkeep of the tests is becoming a burden
=> Support `puppet device --resource ... --to_yaml` invocation; drop puppet4 and jruby 1.7 testing

lib/puppet/resource_api/type_definition.rb, spec/puppet/resource_api/base_type_definition_spec.rb
The method `TypeDefinition#check_schema_values` now includes type checker error messages along with the values which failed validation thereby improving the UX.
=> This PR adds the type checker error message to validation output

.gitignore, puppet-resource_api.gemspec
Prior to this a lot of files that are only needed for CI were shipped. Arguably, the test suite should actually be shipped, but it wasn't previously anyway.
Found while creating an RPM package for this.
I'll admit I haven't tested the integration and please carefully verify if I haven't missed anything.
=> Only ship needed files

lib/puppet/resource_api/data_type_handling.rb, lib/puppet/resource_api/simple_provider.rb, spec/acceptance/optional_ensure_spec.rb, spec/fixtures/test_module/lib/puppet/provider/test_optional_ensure/test_optional_ensure.rb, spec/fixtures/test_module/lib/puppet/type/test_optional_ensure.rb, spec/puppet/resource_api/simple_provider_spec.rb, spec/puppet/resource_api/type_definition_spec.rb
Add support for specifying the ensure parameter as an
Optional Enum data type.
This permits resource properties of types specified this way
to be managed but only if the resource is already present and
cleanly skipped otherwise.
This is a behavior already present in many traditional Puppet
resource types and this extends the option to the Resource API,
easing transition of existing resource types to the Resource API.
=> Support ensure parameter with Optional data type

lib/puppet/resource_api.rb, spec/puppet/resource_api_spec.rb
Add support for autorequire-family variable expansion referencing
parameters with array values. Also, remove any nil values from
results.
=> Add array support to autorequire variable expansion

lib/puppet/resource_api/transport.rb, spec/acceptance/transport/transport_defaults_spec.rb, spec/fixtures/test_module/lib/puppet/transport/schema/test_device_default.rb, spec/fixtures/test_module/lib/puppet/transport/test_device_default.rb, spec/fixtures/test_module/lib/puppet/util/network_device/test_device_default/device.rb, spec/integration/resource_api/transport_spec.rb, spec/puppet/resource_api/transport_spec.rb
Add the ability to specify a default to transport connection_info
attributes which will be used in the event no value for the given
connection_info attribute is provided.
=> (GH-231) Add default to transport attributes

lib/puppet/resource_api/version.rb
We need to release 1.8.15 for the upcoming Puppet 6.27.0 and 7.16.0 releases. [In this commit](https://github.com/puppetlabs/puppet-resource_api/commit/aebad5efd1107c068ab09e33634128efb5751892), our automation accidentally skipped 1.8.15 and went straight to 1.8.16.
After this is merged, I plan on running a package validation pipeline that will add the corresponding 1.8.15 tag.
=> (packaging) Sets version to 1.8.15 for release

CHANGELOG.md, Rakefile
This repo historically used v1.x.x tags, but we stopped tagging with the `v`
prefix in 1.8.2. However, when doing the 1.8.14 release, both 1.8.14 and v1.8.14
tags were created. So this commit excludes the v1.8.14 tag to avoid creating an
empty changelog diff for `v1.8.14...1.8.14`
And it updates the Rakefile to not prefix the future tag with `v`.
Our puppet-agent automation handles tag & bumps for components and doesn't use `v` prefixes, so it's better that resource-api doesn't either.
Also note we [planned on releasing 1.8.15 in 6.27.0 and 7.16.0](2bfa046993305de71901fa55c714b9780501c6c6) but we ended up not doing that:
https://github.com/puppetlabs/puppet-agent/blob/6.27.0/configs/components/puppet-resource_api.json#L1
https://github.com/puppetlabs/puppet-agent/blob/7.16.0/configs/compon …
=> Release 1.8.15

CHANGELOG.md, Rakefile, lib/puppet/resource_api/version.rb
We have to burn 1.8.15 since our automation won't allow bumping to a version
string (1.8.16) that has already been bumped to. See https://github.com/puppetlabs/puppet-resource_api/commit/aebad5efd1107c068ab09e33634128efb5751892. So during
the next release, we will release 1.8.16 and bump to 1.8.17.
=> Update for release 1.8.16

lib/puppet/resource_api/version.rb
User error in release automation meant this bump did not happen; manually bumping here.
=> (packaging) Bump to version '1.8.17' [no-promote]

.github/workflows/rspec_tests.yaml, .rubocop.yml, README.md, lib/puppet/resource_api/base_context.rb, lib/puppet/resource_api/data_type_handling.rb, spec/puppet/resource_api/base_context_spec.rb, spec/puppet/resource_api/simple_provider_spec.rb, spec/puppet/resource_api/transport_spec.rb
This commit updates the versions of Ruby and Puppet that rspec tests run on to include Ruby 3.2 and Puppet 8.
=> (PA-5641) Update rspec tests with modern Ruby

puppet-resource_api.gemspec
This preserves the `git ls-files` behavior of only adding files, and not directories, to `spec.files=`. The motivation for this change is we don't have git installed on all of the platforms for which we build puppet-agent packages.
Inspiration for this change was borrowed from facter[1]
https://github.com/puppetlabs/facter/blob/main/facter.gemspec
=> (maint) Don't require git

Gemfile
This commit removes several conditionals in the Gemfile that refers to older versions of Ruby that are no longer supported by Puppet. At this time of this commit, the oldest version of Ruby supported by Puppet is Ruby 2.7.
=> (maint) Remove old Ruby logic from Gemfile

.github/workflows/release.yaml
There is no need to embed a specific secret token in the project. An action automatically generates a token during its run, and the repository is set to allow tokens read/write permissions.
=> (PA-5641) prefer auto-generated GITHUB_TOKEN

.github/workflows/release.yaml
This commit changes the github release action to only release to rubygems, meaning that the repo should be manually updated in version and will release a gem when a tag is pushed.
=> (PA-5641) Release only to rubygems, do not bump and release

lib/puppet/resource_api.rb, lib/puppet/resource_api/type_definition.rb, spec/puppet/resource_api_spec.rb
Allows the generate function to be utilized in order to manually create an array of types to be enforced.
The `generate` method is called prior to the resource being managed.
There is a second `eval_generate` method that is called after it has been, which may be good to add at a later date.
=> (CAT-761) Add custom_generate as a feature

.github/workflows/checks.yaml, .github/workflows/mend.yaml, .github/workflows/release.yaml, .github/workflows/rspec_tests.yaml, Gemfile
The Checkout GitHub Action v3 uses Node 16, which hit end-of-life on September 11, 2023.
This commit updates all instances of the Checkout Action from v3 to v4.
=> (PA-5803) Update Checkout GitHub Action

CODEOWNERS
DevX team has taken primary ownership of the resource_api tool. Phoenix left as secondary codeowner as they have a stake in the transport section of the tool.
=> (CAT-1533) Set DevX as primary owner

lib/puppet/resource_api.rb, spec/acceptance/composite_namevar_spec.rb, spec/fixtures/test_module/lib/puppet/provider/test_simple_get_filter/test_simple_get_filter.rb, spec/puppet/resource_api_spec.rb
Per issue #303, the Puppet Specification for Resource API indicates that a provider get() method when simple_get_filter is enabled should return all instances when the second/names parameter is set to 'nil'.
Currently, if a Resource API provider is implemented per specification and uses the simple_get_filter feature it will never return any resources for the `instances()` method, which prevents things such a resource purging from working.
=> Fix instances method with simple_get_filter

lib/puppet/resource_api/simple_provider.rb, spec/puppet/resource_api/simple_provider_spec.rb
The SimpleProvider has some support for composite namevars, but it is incomplete and only works in scenarios where the :is value is supplied. This PR adds more comprehensive unit tests which cover scenarios where :is is not passed and fixes these issues. As a bonus, the SimpleProvider now works for types with any namevar (it no longer is required to be `name` for the single-valued case).  Some additional code cleanups are included.
=> SimpleProvider name fixes

CODEOWNERS
When PRs are raised the CODEOWNERS.md is assessed via regex to determine the allowed approvers. The     CODEOWNERS file uses the last matching pattern for each file. In this case, there are two patterns t    hat match all files, and the last one is "@puppetlabs/phoenix". This is why only the Phoenix team is     being requested for review.  To have both teams requested for review, the regex needs to be in one     line like this: "@puppetlabs/devx @puppetlabs/phoenix". This way, both teams will be automatically r    equested for review when a pull request is opened.
=> Ensure devx and phoenix codeowners are PR approvers

Gemfile
Recent rubocop updates broke the resource_api's CI:
```ruby
➜  puppet-resource_api git:(main) bundle exec rubocop
Error: Property AutoCorrect of cop FactoryBot/CreateList is supposed to be a boolean and contextual is not.
+ set +x
➜  puppet-resource_api git:(main) 
```
Although the fix for other repositories was to upgrade rubocop, an upgrade was not possible on this repo because of the `jruby` and `ruby` engine testing.  The solution was to pin the rubocop dependencies to the last working nightly versions:
```ruby
gem 'rubocop', '~> 1.48.1', require: false
gem 'rubocop-rspec', '~> 2.20.0', require: false
gem 'rubocop-performance', '~> 1.17.1', require: false
```
=> Fix rubocop errors

Gemfile
This commit aims to update the severely outdated spec_helper depencency one version at a time until we reach the latest version.
=> (CAT-2113) Update spec_helper version

.gitignore
Following a failed attempt to run a release_prep workflows, we realised that the vendor/ path was missing in the .gitignore file. This caused the release process to add thousands of files to the commit, which was not the intended behaviour.
=> (MAINT) Add vendor/ to .gitignore

CHANGELOG.md
Adjusting the changelogs date structure so that the release process does not freak out when generating release notes.
=> (MAINT) Adjust changelog date structure
